import type { LaravelProject } from './project';

function packageManagerCommands(project: LaravelProject): {
  install: string;
  build: string;
} {
  switch (project.packageManager) {
    case 'pnpm':
      return {
        install: 'corepack enable && pnpm install --frozen-lockfile',
        build: 'pnpm run build',
      };
    case 'yarn':
      return {
        install: 'corepack enable && yarn install --frozen-lockfile',
        build: 'yarn build',
      };
    case 'bun':
      return {
        install: 'npm install --global bun && bun install --frozen-lockfile',
        build: 'bun run build',
      };
    default:
      return {
        install: project.packageLock ? 'npm ci' : 'npm install',
        build: 'npm run build',
      };
  }
}

function extensionInstall(project: LaravelProject): string[] {
  const apt = new Set([
    'libcurl4-openssl-dev',
    'libicu-dev',
    'libxml2-dev',
    'libonig-dev',
    'libpq-dev',
    'libsqlite3-dev',
    'libzip-dev',
    'unzip',
  ]);
  const configure: string[] = [];
  const builtIn = new Set([
    'bcmath',
    'curl',
    'dom',
    'intl',
    'mbstring',
    'opcache',
    'pcntl',
    'pdo_mysql',
    'pdo_pgsql',
    'pdo_sqlite',
    'sockets',
    'simplexml',
    'xml',
    'xmlreader',
    'xmlwriter',
    'zip',
  ]);
  const pecl: string[] = [];

  if (project.extensions.has('gd')) {
    apt.add('libfreetype6-dev');
    apt.add('libjpeg62-turbo-dev');
    apt.add('libpng-dev');
    configure.push('docker-php-ext-configure gd --with-freetype --with-jpeg');
    builtIn.add('gd');
  }
  if (project.extensions.has('soap')) {
    apt.add('libxml2-dev');
    builtIn.add('soap');
  }
  if (project.extensions.has('exif')) {
    builtIn.add('exif');
  }
  if (project.extensions.has('imagick')) {
    apt.add('libmagickwand-dev');
    pecl.push('imagick');
  }
  if (project.extensions.has('redis')) {
    pecl.push('redis');
  }

  return [
    `RUN apt-get update && apt-get install -y --no-install-recommends ${[
      ...apt,
    ].join(' ')} \\`,
    '    && rm -rf /var/lib/apt/lists/*',
    ...configure.map(command => `RUN ${command}`),
    `RUN docker-php-ext-install -j"$(nproc)" ${[...builtIn].join(' ')}`,
    ...(pecl.length
      ? [
          `RUN pecl install ${pecl.join(' ')} \\`,
          `    && docker-php-ext-enable ${pecl.join(' ')}`,
        ]
      : []),
  ];
}

function buildEnvArgs(buildEnv: Record<string, string | undefined>): string[] {
  return Object.keys(buildEnv)
    .filter(key => /^VITE_[A-Z0-9_]+$/.test(key))
    .sort()
    .map(key => `ARG ${key}`);
}

export function generateDockerfile(
  project: LaravelProject,
  buildEnv: Record<string, string | undefined> = {}
): string {
  const assets = packageManagerCommands(project);
  const packageFiles = ['package.json', project.packageLock].filter(Boolean);
  const composerFiles = [
    'composer.json',
    project.composerLock ? 'composer.lock' : undefined,
  ].filter(Boolean);

  return [
    '# syntax=docker/dockerfile:1.7',
    '# Generated by @vercel/laravel. This file is not written to the project.',
    `FROM php:${project.phpVersion}-apache-bookworm AS php-base`,
    ...extensionInstall(project),
    'RUN a2enmod expires headers rewrite \\',
    "    && sed -ri -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf \\",
    "    && sed -ri -e 's!/var/www/!/var/www/html/public!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf",
    'WORKDIR /var/www/html',
    '',
    'FROM node:24-bookworm-slim AS node',
    'FROM composer:2 AS composer',
    '',
    'FROM php-base AS build',
    'COPY --from=node /usr/local/ /usr/local/',
    'COPY --from=composer /usr/bin/composer /usr/local/bin/composer',
    'WORKDIR /app',
    'ARG COMPOSER_AUTH',
    ...buildEnvArgs(buildEnv),
    `COPY ${composerFiles.join(' ')} ./`,
    'RUN composer install --no-dev --no-interaction --no-progress --prefer-dist --no-scripts',
    ...(project.packageManager
      ? [`COPY ${packageFiles.join(' ')} ./`, `RUN ${assets.install}`]
      : []),
    'COPY . .',
    'RUN composer install --no-dev --no-interaction --no-progress --prefer-dist --optimize-autoloader \\',
    '    && php artisan package:discover --ansi',
    ...(project.hasAssetBuild ? [`RUN ${assets.build}`] : []),
    '',
    'FROM php-base AS runtime',
    'ENV APP_ENV=production \\',
    '    APP_DEBUG=false \\',
    '    LOG_CHANNEL=stderr \\',
    '    SESSION_DRIVER=cookie \\',
    '    CACHE_STORE=array \\',
    '    QUEUE_CONNECTION=sync',
    'COPY --from=build --chown=www-data:www-data /app /var/www/html',
    'RUN rm -f /var/www/html/.env \\',
    '    && mkdir -p storage/framework/cache storage/framework/sessions storage/framework/views storage/logs bootstrap/cache \\',
    '    && chown -R www-data:www-data storage bootstrap/cache',
    'EXPOSE 80',
    'CMD ["apache2-foreground"]',
    '',
  ].join('\n');
}
