/**
 * Zod schemas for pyproject.toml configuration types.
 *
 * Types are defined in types.ts (source of truth).
 * Schemas are generated by ts-to-zod and re-exported here with proper typing.
 *
 * @module pyproject/schema
 */

import type { z } from 'zod';

import {
  licenseObjectSchema as generatedLicenseObjectSchema,
  licenseSchema as generatedLicenseSchema,
  personSchema as generatedPersonSchema,
  pyProjectBuildSystemSchema as generatedPyProjectBuildSystemSchema,
  pyProjectDependencyGroupsSchema as generatedPyProjectDependencyGroupsSchema,
  pyProjectProjectSchema as generatedPyProjectProjectSchema,
  pyProjectTomlSchema as generatedPyProjectTomlSchema,
  pyProjectToolSectionSchema as generatedPyProjectToolSectionSchema,
  readmeObjectSchema as generatedReadmeObjectSchema,
  readmeSchema as generatedReadmeSchema,
} from './schema.zod';

import type {
  License,
  LicenseObject,
  Person,
  PyProjectBuildSystem,
  PyProjectDependencyGroups,
  PyProjectProject,
  PyProjectToml,
  PyProjectToolSection,
  Readme,
  ReadmeObject,
} from './types';

/**
 * Schema for [build-system] per PEP 518.
 */
export const PyProjectBuildSystemSchema =
  generatedPyProjectBuildSystemSchema.passthrough() as z.ZodType<PyProjectBuildSystem>;

/**
 * Schema for author/maintainer entries.
 */
export const PersonSchema =
  generatedPersonSchema.passthrough() as z.ZodType<Person>;

/**
 * Schema for readme field as an object.
 */
export const ReadmeObjectSchema =
  generatedReadmeObjectSchema.passthrough() as z.ZodType<ReadmeObject>;

/**
 * Schema for readme field (can be string or object).
 */
export const ReadmeSchema = generatedReadmeSchema as z.ZodType<Readme>;

/**
 * Schema for license field as an object.
 */
export const LicenseObjectSchema =
  generatedLicenseObjectSchema.passthrough() as z.ZodType<LicenseObject>;

/**
 * Schema for license field (can be string or object).
 */
export const LicenseSchema = generatedLicenseSchema as z.ZodType<License>;

/**
 * Schema for core PEP 621 fields for [project].
 */
export const PyProjectProjectSchema =
  generatedPyProjectProjectSchema.passthrough() as z.ZodType<PyProjectProject>;

/**
 * Schema for [dependency-groups].
 */
export const PyProjectDependencyGroupsSchema =
  generatedPyProjectDependencyGroupsSchema as z.ZodType<PyProjectDependencyGroups>;

/**
 * Schema for [tool.FOO] section.
 */
export const PyProjectToolSectionSchema =
  generatedPyProjectToolSectionSchema.passthrough() as z.ZodType<PyProjectToolSection>;

/**
 * Schema for a pyproject.toml file.
 */
export const PyProjectTomlSchema =
  generatedPyProjectTomlSchema.passthrough() as z.ZodType<PyProjectToml>;
