import { describe, it, expect } from 'vitest';
import { commands } from '../../../src/commands';
describe('index', () => {
  it('outputs a map of what aliases our commands use', () => {
    expect(commands).toEqual(
      new Map([
        ['alias', 'alias'],
        ['aliases', 'alias'],
        ['bisect', 'bisect'],
        ['blob', 'blob'],
        ['build', 'build'],
        ['cache', 'cache'],
        ['cert', 'certs'],
        ['certs', 'certs'],
        ['deploy', 'deploy'],
        ['dev', 'dev'],
        ['develop', 'dev'],
        ['dns', 'dns'],
        ['domain', 'domains'],
        ['domains', 'domains'],
        ['env', 'env'],
        ['git', 'git'],
        ['help', 'help'],
        ['i', 'install'],
        ['init', 'init'],
        ['inspect', 'inspect'],
        ['install', 'install'],
        ['integration', 'integration'],
        ['integration-resource', 'integration-resource'],
        ['ir', 'integration-resource'],
        ['link', 'link'],
        ['list', 'list'],
        ['ln', 'alias'],
        ['log', 'logs'],
        ['login', 'login'],
        ['logout', 'logout'],
        ['logs', 'logs'],
        ['ls', 'list'],
        ['mcp', 'mcp'],
        ['mf', 'microfrontends'],
        ['microfrontends', 'microfrontends'],
        ['project', 'project'],
        ['projects', 'project'],
        ['promote', 'promote'],
        ['pull', 'pull'],
        ['redeploy', 'redeploy'],
        ['remove', 'remove'],
        ['rm', 'remove'],
        ['rollback', 'rollback'],
        ['rolling-release', 'rolling-release'],
        ['rr', 'rolling-release'],
        ['switch', 'teams'],
        ['target', 'target'],
        ['targets', 'target'],
        ['team', 'teams'],
        ['teams', 'teams'],
        ['telemetry', 'telemetry'],
        ['whoami', 'whoami'],
      ])
    );
  });
});
