packages:
  - 'packages/*'
  - 'api'
  - 'examples'
  - 'internals/*'
  - 'python/vercel-runtime'
  - 'python/vercel-workers'

minimumReleaseAge: 2880 # 2 days

minimumReleaseAgeExclude:
  - '@next-community/adapter-vercel'
  - '@next/*'
  - '@turbo/*'
  - '@vercel/*'
  - 'next'
  - 'sandbox'
  - 'turbo'
