/**
 * Zod schemas for Python dependency requirement types.
 *
 * Types are defined in types.ts (source of truth).
 * Schemas are generated by ts-to-zod and re-exported here with proper typing.
 *
 * @module requirement/schema
 */

import type { z } from 'zod';

import {
  dependencySourceSchema as generatedDependencySourceSchema,
  normalizedRequirementSchema as generatedNormalizedRequirementSchema,
  hashDigestSchema,
} from './schema.zod';

import type {
  DependencySource,
  HashDigest,
  NormalizedRequirement,
} from './types';

/**
 * Schema for dependency source information (git, path, or index).
 * Used in [tool.uv.sources] in pyproject.toml.
 */
export const DependencySourceSchema =
  generatedDependencySourceSchema.passthrough() as z.ZodType<DependencySource>;

/**
 * Schema for a normalized representation of a Python dependency.
 * This is the common format used by all parsers before converting to PEP 508 format.
 *
 * Note: This schema uses the generated version without passthrough since
 * NormalizedRequirement is an internal type with a known structure.
 */
export const NormalizedRequirementSchema =
  generatedNormalizedRequirementSchema as z.ZodType<NormalizedRequirement>;

/**
 * Schema for parsed hash digest for a requirement.
 * Format: algorithm:hash_value (e.g., "sha256:abc123...")
 */
export const HashDigestSchema = hashDigestSchema as z.ZodType<HashDigest>;
