body:
  - type: markdown
    attributes:
      value: |
        # Please go to Vercel Community
        > [!IMPORTANT]  
        > **New Discussions in this repo are no longer actively monitored and will be automatically closed. Please go to the new [Vercel Community](https://vercel.community).**
  - type: textarea
    attributes:
      label: Question
    validations:
      required: true
