import { spawn } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { startFakeApi, type FakeApi } from './fake-api';

const harnessDir = dirname(fileURLToPath(import.meta.url));
const cliRoot = join(harnessDir, '..', '..', '..');
const startScript = join(cliRoot, 'scripts', 'start.js');
const distEntry = join(cliRoot, 'dist', 'index.js');
export const guardPath = join(harnessDir, 'guard.cjs');

export interface GuardViolation {
  kind: string;
  target: string;
}

export interface CliScenarioResult {
  exitCode: number | null;
  signal: NodeJS.Signals | null;
  stdout: string;
  stderr: string;
  guardViolations: GuardViolation[];
  durationMs: number;
}

export interface ScenarioSandbox {
  root: string;
  home: string;
  workspace: string;
  globalConfig: string;
  guardLog: string;
  writeJson(path: string, value: unknown): void;
}

export interface ScenarioContext {
  api: FakeApi;
  sandbox: ScenarioSandbox;
  run(options: RunCliOptions): Promise<CliScenarioResult>;
}

export interface RunCliOptions {
  args: string[];
  /** Synthetic token passed with `--token`; omit it to use temp auth config. */
  token?: string;
  /**
   * Run with the CLI's production API origin (no `--api`) and let the guard
   * route `https://vercel.com` and `https://api.vercel.com` to the fake API.
   */
  routeProductionOrigins?: boolean;
  env?: Record<string, string>;
  timeoutMs?: number;
}

/**
 * Scenario tests execute `dist`, never source. CI builds it through Turbo's
 * `test-unit -> build:package -> build` dependency. Locally, run `pnpm build`.
 */
export function assertBuiltCli() {
  if (!existsSync(distEntry)) {
    throw new Error(
      `Scenario tests require a built CLI at ${distEntry}. Run \`pnpm build\` in packages/cli.`
    );
  }

  // Turbo cache restores may not preserve source-relative mtimes in CI, where
  // the task graph already makes the build explicit.
  if (process.env.CI) return;

  const builtAt = statSync(distEntry).mtimeMs;
  const newest = newestInput([
    join(cliRoot, 'src'),
    join(cliRoot, 'package.json'),
    join(cliRoot, 'scripts', 'build.mjs'),
  ]);
  if (newest.mtimeMs > builtAt) {
    throw new Error(
      `Scenario tests require a fresh CLI build; ${newest.path} is newer than dist. Run \`pnpm build\` in packages/cli.`
    );
  }
}

function newestInput(paths: string[]): { path: string; mtimeMs: number } {
  let newest = { path: '', mtimeMs: 0 };
  const visit = (path: string) => {
    const stat = statSync(path);
    if (stat.isDirectory()) {
      for (const entry of readdirSync(path)) visit(join(path, entry));
      return;
    }
    // Generated by `scripts/build.mjs` before bundling.
    if (path.endsWith(join('src', 'util', 'constants.ts'))) return;
    if (stat.mtimeMs > newest.mtimeMs) newest = { path, mtimeMs: stat.mtimeMs };
  };
  paths.forEach(visit);
  return newest;
}

function createSandbox(): ScenarioSandbox {
  const root = mkdtempSync(join(tmpdir(), 'vercel-cli-scenario-'));
  const home = join(root, 'home');
  const workspace = join(root, 'workspace');
  const globalConfig = join(root, 'global-config');
  const guardLog = join(root, 'guard.log');
  for (const dir of [
    home,
    workspace,
    globalConfig,
    join(root, 'tmp'),
    join(home, '.config'),
    join(home, '.local', 'share'),
    join(home, '.cache'),
    join(home, '.local', 'state'),
  ]) {
    mkdirSync(dir, { recursive: true });
  }
  writeFileSync(guardLog, '');

  const sandbox = {
    root,
    home,
    workspace,
    globalConfig,
    guardLog,
    writeJson(path: string, value: unknown) {
      const target = join(root, path);
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, `${JSON.stringify(value, null, 2)}\n`);
    },
  };

  sandbox.writeJson('global-config/config.json', { credStorage: 'file' });
  // A workspace-root repo link stops `findRepoRoot` before its Git fallback.
  sandbox.writeJson('workspace/.vercel/repo.json', {
    remoteName: 'origin',
    projects: [],
  });
  return sandbox;
}

function childEnv(
  sandbox: ScenarioSandbox,
  api: FakeApi,
  extra: Record<string, string>
): NodeJS.ProcessEnv {
  const tmp = join(sandbox.root, 'tmp');
  return {
    // Keep only platform variables required to start Node on Windows.
    ...(process.env.SystemRoot ? { SystemRoot: process.env.SystemRoot } : {}),
    HOME: sandbox.home,
    USERPROFILE: sandbox.home,
    XDG_CONFIG_HOME: join(sandbox.home, '.config'),
    XDG_DATA_HOME: join(sandbox.home, '.local', 'share'),
    XDG_CACHE_HOME: join(sandbox.home, '.cache'),
    XDG_STATE_HOME: join(sandbox.home, '.local', 'state'),
    TMPDIR: tmp,
    TMP: tmp,
    TEMP: tmp,
    VERCEL_TELEMETRY_DISABLED: '1',
    NO_UPDATE_NOTIFIER: '1',
    NO_COLOR: '1',
    FORCE_COLOR: '0',
    VERCEL_SCENARIO_GUARD_LOG: sandbox.guardLog,
    VERCEL_SCENARIO_GUARD_PORT: new URL(api.origin).port,
    ...extra,
  };
}

function readGuardViolations(path: string): GuardViolation[] {
  return readFileSync(path, 'utf8')
    .split('\n')
    .filter(Boolean)
    .map(line => JSON.parse(line) as GuardViolation);
}

export async function runNodeWithGuard(
  script: string,
  args: string[],
  sandbox: ScenarioSandbox,
  api: FakeApi,
  { env = {}, timeoutMs = 30_000 }: Pick<RunCliOptions, 'env' | 'timeoutMs'>
): Promise<CliScenarioResult> {
  const startedAt = performance.now();
  const child = spawn(
    process.execPath,
    ['--require', guardPath, script, ...args],
    {
      cwd: sandbox.workspace,
      env: childEnv(sandbox, api, env),
      shell: false,
      stdio: ['ignore', 'pipe', 'pipe'],
    }
  );
  let stdout = '';
  let stderr = '';
  child.stdout.setEncoding('utf8').on('data', chunk => (stdout += chunk));
  child.stderr.setEncoding('utf8').on('data', chunk => (stderr += chunk));

  const timeout = setTimeout(() => child.kill('SIGKILL'), timeoutMs);
  const [exitCode, signal] = await new Promise<
    [number | null, NodeJS.Signals | null]
  >((resolve, reject) => {
    child.on('error', reject);
    child.on('close', (code, closeSignal) => resolve([code, closeSignal]));
  }).finally(() => clearTimeout(timeout));

  return {
    exitCode,
    signal,
    stdout,
    stderr,
    guardViolations: readGuardViolations(sandbox.guardLog),
    durationMs: performance.now() - startedAt,
  };
}

/**
 * Runs one isolated scenario with a fresh fake API and temp application state.
 * Resources are closed even when assertions inside `body` fail.
 */
export async function withScenario(
  body: (context: ScenarioContext) => Promise<void>
): Promise<void> {
  const api = await startFakeApi();
  const sandbox = createSandbox();
  try {
    await body({
      api,
      sandbox,
      run: ({ args, token, routeProductionOrigins, env, timeoutMs }) =>
        runNodeWithGuard(
          startScript,
          [
            ...args,
            ...(routeProductionOrigins ? [] : ['--api', api.origin]),
            '--global-config',
            sandbox.globalConfig,
            '--cwd',
            sandbox.workspace,
            ...(token === undefined ? [] : ['--token', token]),
          ],
          sandbox,
          api,
          {
            env: {
              ...(routeProductionOrigins
                ? { VERCEL_SCENARIO_ROUTE_PRODUCTION: '1' }
                : {}),
              ...env,
            },
            ...(timeoutMs === undefined ? {} : { timeoutMs }),
          }
        ),
    });
  } finally {
    await api.close();
    rmSync(sandbox.root, { recursive: true, force: true });
  }
}

/** Formats failure diagnostics without request bodies, which may contain tokens. */
export function describeRun(result: CliScenarioResult, api: FakeApi): string {
  return JSON.stringify(
    {
      exitCode: result.exitCode,
      signal: result.signal,
      stdout: result.stdout,
      stderr: result.stderr,
      guardViolations: result.guardViolations,
      requests: api.requests.map(({ method, path, query }) => ({
        method,
        path,
        query,
      })),
      unhandled: api.unhandled.map(({ method, path }) => `${method} ${path}`),
    },
    null,
    2
  );
}
