/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectMembersAdd } from "../funcs/projectMembersAdd.js";
import { projectMembersGet } from "../funcs/projectMembersGet.js";
import { projectMembersRemove } from "../funcs/projectMembersRemove.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ProjectMembers extends ClientSDK {
  /**
   * List project members
   *
   * @remarks
   * Lists all members of a project.
   */
  async get(
    request: operations.GetProjectMembersRequest,
    options?: RequestOptions,
  ): Promise<operations.GetProjectMembersResponseBody> {
    return unwrapAsync(projectMembersGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Adds a new member to a project.
   *
   * @remarks
   * Adds a new member to the project.
   */
  async add(
    request: operations.AddProjectMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.AddProjectMemberResponseBody> {
    return unwrapAsync(projectMembersAdd(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a Project Member
   *
   * @remarks
   * Remove a member from a specific project
   */
  async remove(
    request: operations.RemoveProjectMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.RemoveProjectMemberResponseBody> {
    return unwrapAsync(projectMembersRemove(
      this,
      request,
      options,
    ));
  }
}
