/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { secretsCreate } from "../funcs/secretsCreate.js";
import { secretsDelete } from "../funcs/secretsDelete.js";
import { secretsGet } from "../funcs/secretsGet.js";
import { secretsList } from "../funcs/secretsList.js";
import { secretsRename } from "../funcs/secretsRename.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Secrets extends ClientSDK {
  /**
   * List secrets
   *
   * @remarks
   * Retrieves the active Vercel secrets for the authenticated user or team. By default it returns 20 secrets. The rest can be retrieved using the pagination options. The body will contain an entry for each secret.
   */
  async list(
    request: operations.GetSecretsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSecretsResponseBody> {
    return unwrapAsync(secretsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new secret
   *
   * @remarks
   * Allows to create a new secret.
   */
  async create(
    request: operations.CreateSecretRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateSecretResponseBody> {
    return unwrapAsync(secretsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Change secret name
   *
   * @remarks
   * Enables to edit the name of a secret. The name has to be unique to the user or team’s secrets.
   */
  async rename(
    request: operations.RenameSecretRequest,
    options?: RequestOptions,
  ): Promise<operations.RenameSecretResponseBody> {
    return unwrapAsync(secretsRename(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single secret
   *
   * @remarks
   * Retrieves the information for a specific secret by passing either the secret id or name in the URL.
   */
  async get(
    request: operations.GetSecretRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSecretResponseBody> {
    return unwrapAsync(secretsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a secret
   *
   * @remarks
   * This deletes the user or team’s secret defined in the URL.
   */
  async delete(
    request: operations.DeleteSecretRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteSecretResponseBody> {
    return unwrapAsync(secretsDelete(
      this,
      request,
      options,
    ));
  }
}
