export const mapOldToNew: { [key: string]: string[] } = {
  'go-image-to-ascii': ['vanilla-functions'],
  markdown: ['hexo', 'docusaurus', 'docz', 'jekyll'],
  'mdx-deck': ['docz'],
  'mdx-deck-advanced': ['docz'],
  'nextjs-mysql': ['nextjs'],
  'nextjs-news': ['nextjs'],
  'nextjs-nodejs-mongodb': ['nextjs'],
  'nextjs-static': ['nextjs'],
  'node-server': ['svelte-functions'],
  nodejs: ['svelte-functions'],
  'nodejs-canvas-partyparrot': ['svelte-functions'],
  'nodejs-coffee': ['svelte-functions'],
  'nodejs-hapi': ['svelte-functions'],
  'nodejs-koa': ['svelte-functions'],
  'nodejs-koa-ts': ['gatsby-functions'],
  'nodejs-micro': ['svelte-functions'],
  'nodejs-ms-graph-security-api': ['svelte-functions'],
  'nodejs-pdfkit': ['svelte-functions'],
  'nodejs-ts': ['gatsby-functions'],
  'nuxt-static': ['nuxtjs'],
  static: ['vanilla'],
  typescript: ['gatsby-functions'],
  umi: ['umijs'],
  'vanilla-go': ['vanilla-functions'],
  'vanilla-json-api': ['svelte-functions'],
  'vue-ssr': ['vue'],
};
