name: Vercel CLI Bug Report
description: File a bug report for the `vercel` CLI
body:
  - type: markdown
    attributes:
      value: |
        *Thanks for reaching out!* We use this Issue tracker for issues with the Vercel CLI and related open source libraries. If you are experiencing an issue with the Vercel CLI please delete this text and describe your issue.

        *For general platform help and feedback please open a new discussion at https://vercel.community.*
