"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=nns2j5&xri3pl^+w^&(z$y(kt&j8zfist4ll+r68t@)22fg3_"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

vercel_url = os.environ.get("VERCEL_URL")
vercel_production_url = os.environ.get("VERCEL_PROJECT_PRODUCTION_URL")
allowed_hosts: list[str] = os.environ.get("ALLOWED_HOSTS", "").split(",")
if vercel_url:
    allowed_hosts.append(vercel_url)
if vercel_production_url:
    allowed_hosts.append(vercel_production_url)
# Allow localhost for local development
allowed_hosts.extend(["localhost", "127.0.0.1"])
ALLOWED_HOSTS = allowed_hosts


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# =============================================================================
# Django Tasks Configuration
# https://docs.djangoproject.com/en/6.0/topics/tasks/
# =============================================================================
#
# This configures Vercel Queues as the backend for Django's tasks framework.
# Tasks enqueued via `my_task.enqueue(...)` will be sent to Vercel Queues.
#
# On Vercel: Queue triggers will POST to your callback route, which executes the task.
# Locally: Use the polling worker or the ImmediateBackend for development.

TASKS = {
    "default": {
        "BACKEND": "vercel.workers.django.VercelQueuesBackend",
        # Restrict which queues this backend will process (security measure).
        "QUEUES": ["django-tasks"],
        "OPTIONS": {
            # Task execution options
            "visibility_timeout_seconds": 30,
            "visibility_refresh_interval_seconds": 10.0,
            "timeout": 10.0,
            # Retry policy
            "max_attempts": 4,
            "retry_backoff_base_seconds": 3,
            "retry_backoff_factor": 1.5,
            "max_retry_delay_seconds": 1000,
            # Result storage (uses Django's cache)
            "cache_alias": "default",
            "cache_key_prefix": "vercel-workers:django-tasks",
            "result_ttl_seconds": 86400,  # 24 hours
        },
    },
}

# Cache configuration for storing task results.
# In production, use Redis or another shared cache for cross-process result access.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "django-tasks",
    }
}
