export {
  detectServices,
  generateServiceRewrites,
  generateServicesRoutes,
  resolveAllConfiguredServicesV2,
  resolveConfiguredServiceV2,
  validateServiceConfigV2,
  autoDetectServices,
  isStaticBuild,
  isRouteOwningBuilder,
  INTERNAL_SERVICE_PREFIX,
  getInternalServiceFunctionPath,
  getInternalServiceCronPath,
  getInternalServiceCronPathPrefix,
  getInternalServiceWorkerPath,
  getInternalServiceWorkerPathPrefix,
  isExperimentalService,
  isExperimentalServiceV2,
} from '@vercel/fs-detectors';
export type {
  AutoDetectOptions,
  AutoDetectResult,
  DetectServicesOptions,
  DetectServicesResult,
  DetectServicesSource,
  InferredServiceConfig,
  InferredServicesConfig,
  ResolvedServicesResult,
  InferredServicesResult,
  ResolvedService,
  Service,
  ExperimentalService,
  ExperimentalServiceV2,
  ExperimentalServiceV2Config,
  ExperimentalServicesV2,
  ExperimentalServiceV2Binding,
  ServiceBinding,
  ServiceConfig,
  Services,
  ServicesRoutes,
  ServiceDetectionError,
  ConfiguredServices,
  ConfiguredServicesType,
} from '@vercel/fs-detectors';
