/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteEdgeConfigSchemaRequest = {
  edgeConfigId: string;
  /**
   * The Team identifier to perform the request on behalf of.
   */
  teamId?: string | undefined;
  /**
   * The Team slug to perform the request on behalf of.
   */
  slug?: string | undefined;
};

/** @internal */
export const DeleteEdgeConfigSchemaRequest$inboundSchema: z.ZodType<
  DeleteEdgeConfigSchemaRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  edgeConfigId: z.string(),
  teamId: z.string().optional(),
  slug: z.string().optional(),
});

/** @internal */
export type DeleteEdgeConfigSchemaRequest$Outbound = {
  edgeConfigId: string;
  teamId?: string | undefined;
  slug?: string | undefined;
};

/** @internal */
export const DeleteEdgeConfigSchemaRequest$outboundSchema: z.ZodType<
  DeleteEdgeConfigSchemaRequest$Outbound,
  z.ZodTypeDef,
  DeleteEdgeConfigSchemaRequest
> = z.object({
  edgeConfigId: z.string(),
  teamId: z.string().optional(),
  slug: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteEdgeConfigSchemaRequest$ {
  /** @deprecated use `DeleteEdgeConfigSchemaRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteEdgeConfigSchemaRequest$inboundSchema;
  /** @deprecated use `DeleteEdgeConfigSchemaRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteEdgeConfigSchemaRequest$outboundSchema;
  /** @deprecated use `DeleteEdgeConfigSchemaRequest$Outbound` instead. */
  export type Outbound = DeleteEdgeConfigSchemaRequest$Outbound;
}
