/**
 * Zod schemas for Vercel global config types.
 *
 * Types are defined in types.ts (source of truth).
 * Schemas are generated by ts-to-zod and re-exported here with runtime
 * passthrough behavior for unrecognized config keys.
 */

import type { z } from 'zod';
import {
  authConfigSchema as generatedAuthConfigSchema,
  globalConfigSchema as generatedGlobalConfigSchema,
  guidanceConfigSchema as generatedGuidanceConfigSchema,
  telemetryConfigSchema as generatedTelemetryConfigSchema,
  updatesConfigSchema as generatedUpdatesConfigSchema,
} from './schema.zod';
import type {
  AuthConfig,
  GlobalConfig,
  GuidanceConfig,
  TelemetryConfig,
  UpdatesConfig,
} from './types';

export const telemetryConfigSchema =
  generatedTelemetryConfigSchema.passthrough() as z.ZodType<TelemetryConfig>;

export const guidanceConfigSchema =
  generatedGuidanceConfigSchema.passthrough() as z.ZodType<GuidanceConfig>;

export const updatesConfigSchema =
  generatedUpdatesConfigSchema.passthrough() as z.ZodType<UpdatesConfig>;

export const globalConfigSchema = generatedGlobalConfigSchema
  .extend({
    telemetry: telemetryConfigSchema.optional(),
    guidance: guidanceConfigSchema.optional(),
    updates: updatesConfigSchema.optional(),
  })
  .passthrough() as z.ZodType<GlobalConfig>;

export const authConfigSchema =
  generatedAuthConfigSchema.passthrough() as z.ZodType<AuthConfig>;
