import { join } from 'path';
import { existsSync, promises } from 'fs';

import type { Framework } from './types';
import { readConfigFile } from './read-config-file';

const { readdir, readFile, unlink } = promises;

/**
 * Behavioral overrides for framework entries whose `getOutputDirName` or
 * `defaultRoutes` cannot be represented declaratively in `frameworks.json`.
 *
 * Keyed by framework slug. The interpreter applies these on top of the
 * declarative manifest. This is intentionally a small, enumerable set —
 * new frameworks should prefer declarative fields (a constant
 * `outputDirName` and array `defaultRoutes`) so they can ship via the
 * manifest without a CLI release.
 */

type OutputDirOverride = Framework['getOutputDirName'];
type DefaultRoutesOverride = Framework['defaultRoutes'];

/**
 * Returns `join(base, onlyChildDir)` when `base` contains exactly one entry
 * and that entry is a directory; otherwise returns `base`. Shared by the
 * Docusaurus presets.
 */
const singleSubdir =
  (base: string): OutputDirOverride =>
  async (dirPrefix: string) => {
    try {
      const location = join(dirPrefix, base);
      const content = await readdir(location, { withFileTypes: true });
      if (content.length === 1 && content[0].isDirectory()) {
        return join(base, content[0].name);
      }
    } catch (error) {
      console.error(`Error detecting output directory: `, error);
    }
    return base;
  };

export const outputDirOverrides: Record<string, OutputDirOverride> = {
  'docusaurus-2': singleSubdir('build'),
  docusaurus: singleSubdir('build'),
  angular: async (dirPrefix: string) => {
    const base = 'dist';
    try {
      const location = join(dirPrefix, base);
      const content = await readdir(location, { withFileTypes: true });
      // If there is only one file in it that is a dir we'll use it as dist dir
      if (content.length === 1 && content[0].isDirectory()) {
        const potentialOutDir = join(base, content[0].name);
        const potentialOutDirWithBrowser = join(potentialOutDir, 'browser');
        return existsSync(potentialOutDirWithBrowser)
          ? potentialOutDirWithBrowser
          : potentialOutDir;
      }
    } catch (error) {
      console.error(`Error detecting output directory: `, error);
    }
    return base;
  },
  polymer: async (dirPrefix: string) => {
    const base = 'build';
    try {
      const location = join(dirPrefix, base);
      const content = await readdir(location);
      const paths = content.filter(item => !item.includes('.'));
      return join(base, paths[0]);
    } catch (error) {
      console.error(`Error detecting output directory: `, error);
    }
    return base;
  },
  hugo: async (dirPrefix: string): Promise<string> => {
    type HugoConfig = { publishDir?: string };
    const config = await readConfigFile<HugoConfig>(
      ['config.json', 'config.yaml', 'config.toml'].map(fileName => {
        return join(dirPrefix, fileName);
      })
    );
    return (config && config.publishDir) || 'public';
  },
  jekyll: async (dirPrefix: string): Promise<string> => {
    type JekyllConfig = { destination?: string };
    const config = await readConfigFile<JekyllConfig>(
      join(dirPrefix, '_config.yml')
    );
    return (config && config.destination) || '_site';
  },
};

export const defaultRoutesOverrides: Record<string, DefaultRoutesOverride> = {
  gatsby: async (dirPrefix: string) => {
    // This file could be generated by gatsby-plugin-now or gatsby-plugin-zeit-now
    try {
      const nowRoutesPath = join(
        dirPrefix,
        'public',
        '__now_routes_g4t5bY.json'
      );
      const content = await readFile(nowRoutesPath, 'utf8');
      const nowRoutes = JSON.parse(content);
      try {
        await unlink(nowRoutesPath);
      } catch (_err) {
        // do nothing if deleting the file fails
      }
      return nowRoutes;
    } catch (_err) {
      // if the file doesn't exist, we implement gatsby's recommendations
      // https://www.gatsbyjs.org/docs/caching
      return [
        {
          src: '^/static/(.*)$',
          headers: { 'cache-control': 'public,max-age=31536000,immutable' },
          continue: true,
        },
        {
          src: '^/.*\\.(js|css)$',
          headers: { 'cache-control': 'public,max-age=31536000,immutable' },
          continue: true,
        },
        {
          src: '^/(sw\\.js|app-data\\.json|.*\\.html|page-data/.*)$',
          headers: { 'cache-control': 'public,max-age=0,must-revalidate' },
          continue: true,
        },
        {
          handle: 'filesystem',
        },
        {
          src: '.*',
          status: 404,
          dest: '404.html',
        },
      ];
    }
  },
};
