#!/usr/bin/env zsh
set -euo pipefail

# ── Config ───────────────────────────────────────────────────────────
REPO_ROOT="${0:A:h:h}"
DEMO_OLD="$HOME/demo-old"
DEMO_NEW="$HOME/demo-new"
OLD_VERSION="39.3.0"
ZSHRC="$HOME/.zshrc"
MARKER_START="# ── cli-demo-vc ──"
MARKER_END="# ── /cli-demo-vc ──"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

step() { echo "\n${GREEN}▶ $1${NC}" }
warn() { echo "${YELLOW}⚠ $1${NC}" }
fail() { echo "${RED}✗ $1${NC}"; exit 1 }
ok()   { echo "${GREEN}✓ $1${NC}" }

# ── 1. Create directories + git init ─────────────────────────────────
step "Creating demo directories"
GITIGNORE_CONTENT="*\n!.gitignore"
for dir in "$DEMO_OLD" "$DEMO_NEW"; do
  mkdir -p "$dir"
  if [[ ! -d "$dir/.git" ]]; then
    git -C "$dir" init -q -b main
  fi
  # Always ensure .gitignore is up to date
  echo "$GITIGNORE_CONTENT" > "$dir/.gitignore"
  # Commit everything so repos are clean
  git -C "$dir" add -A
  if ! git -C "$dir" diff --cached --quiet 2>/dev/null; then
    git -C "$dir" commit -m "setup" -q
    ok "$dir (committed)"
  else
    ok "$dir (already clean)"
  fi
done

# ── 2. Install old CLI ──────────────────────────────────────────────
step "Installing vercel@$OLD_VERSION in $DEMO_OLD"

# Ensure standalone package.json so pnpm doesn't think this is a workspace
if [[ ! -f "$DEMO_OLD/package.json" ]]; then
  echo '{"private":true}' > "$DEMO_OLD/package.json"
fi

if [[ -f "$DEMO_OLD/node_modules/.bin/vercel" ]]; then
  INSTALLED=$("$DEMO_OLD/node_modules/.bin/vercel" --version 2>/dev/null || echo "unknown")
  if [[ "$INSTALLED" == *"$OLD_VERSION"* ]]; then
    ok "Already installed: $INSTALLED"
  else
    warn "Wrong version ($INSTALLED), reinstalling..."
    (cd "$DEMO_OLD" && pnpm install "vercel@$OLD_VERSION")
    ok "Installed vercel@$OLD_VERSION"
  fi
else
  (cd "$DEMO_OLD" && pnpm install "vercel@$OLD_VERSION")
  ok "Installed vercel@$OLD_VERSION"
fi

# ── 3. Build new CLI from source ────────────────────────────────────
step "Building new CLI from $REPO_ROOT"
(cd "$REPO_ROOT" && pnpm --filter vercel... build)
if [[ -f "$REPO_ROOT/packages/cli/dist/index.js" ]]; then
  ok "Built: packages/cli/dist/index.js"
else
  fail "Build failed — dist/index.js not found"
fi

# ── 4. Install vc function in .zshrc ────────────────────────────────
step "Installing vc function in $ZSHRC"

# Build the block
VC_BLOCK="$MARKER_START
# Auto-generated by demo/setup.sh — safe to delete this whole block
vc() {
  case \"\$PWD\" in
    $DEMO_OLD*)
      $DEMO_OLD/node_modules/.bin/vercel \"\$@\"
      ;;
    $DEMO_NEW*)
      FF_AUTO_PROVISION_INSTALL=1 node $REPO_ROOT/packages/cli/dist/index.js \"\$@\"
      ;;
    *)
      echo \"vc: not in a demo directory (~/demo-old or ~/demo-new)\"
      return 1
      ;;
  esac
}
$MARKER_END"

# Remove existing block if present, then append fresh
if grep -q "$MARKER_START" "$ZSHRC" 2>/dev/null; then
  # Delete everything between markers (inclusive)
  perl -i -0pe "s/\Q$MARKER_START\E.*?\Q$MARKER_END\E\n?//s" "$ZSHRC"
  ok "Removed old vc block from .zshrc"
fi

echo "\n$VC_BLOCK" >> "$ZSHRC"
ok "Appended vc block to .zshrc"

# ── 5. Check project links ──────────────────────────────────────────
step "Checking project links"
for dir in "$DEMO_OLD" "$DEMO_NEW"; do
  if [[ -f "$dir/.vercel/project.json" ]]; then
    ok "$(basename "$dir") is linked"
  else
    warn "$(basename "$dir") is NOT linked — run: cd $dir && vercel link"
  fi
done

# ── 6. Sanity checks ────────────────────────────────────────────────
step "Sanity checks"

OLD_VER=$("$DEMO_OLD/node_modules/.bin/vercel" --version 2>/dev/null || echo "FAILED")
echo "  Old CLI: $OLD_VER"

NEW_VER=$(node "$REPO_ROOT/packages/cli/dist/index.js" --version 2>/dev/null || echo "FAILED")
echo "  New CLI: $NEW_VER"

if [[ "$OLD_VER" == *"$OLD_VERSION"* ]]; then
  ok "Old version correct"
else
  warn "Old version mismatch: expected $OLD_VERSION, got $OLD_VER"
fi

echo ""
echo "${GREEN}═══════════════════════════════════════════════${NC}"
echo "${GREEN}  Setup complete. Open new terminal tabs, then:${NC}"
echo "${GREEN}═══════════════════════════════════════════════${NC}"
echo ""
echo "  Left pane:   cd ~/demo-old && vc integration add upstash"
echo "  Right pane:  cd ~/demo-new && vc integration add upstash/upstash-kv"
echo ""
echo "  To remove: delete the '$MARKER_START' block from ~/.zshrc"
echo ""
