name: Canary

on:
  push:
    branches:
      - main

env:
  TURBO_REMOTE_ONLY: 'true'
  TURBO_TEAM: 'vercel'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  canary:
    name: Canary
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@e081816240890017053eacbb1bdf337761dc5582 # 1.95.0
        with:
          targets: wasm32-wasip2

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: 'pyproject.toml'

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          version: '0.10.11'

      - name: install npm@11
        run: npm i -g npm@11

      - name: install pnpm@8.3.1
        run: npm i -g pnpm@8.3.1

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Canary Snapshot Versions
        run: pnpm ci:version:canary

      - name: Build Packages
        run: pnpm build
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Publish Canary Snapshots to npm
        run: pnpm ci:publish:canary
        env:
          NPM_CONFIG_PROVENANCE: 'true'
