import { CUSTOM_ALERT_EVENT_HELP } from './schema-help';

export function getRulesAddBodyExamplesHelp(): string {
  return [
    '  Body examples:',
    '  The alert rules API validates the rule body and returns schema errors.',
    '  Run `vercel alerts rules schema --type <type>` for a field reference.',
    '',
    '  Custom alert metric discovery:',
    ...CUSTOM_ALERT_EVENT_HELP.map(line => `  ${line}`),
    '',
    '  Built-in usage anomaly rule:',
    '',
    '    {',
    '      "name": "Production usage anomalies",',
    '      "alertTypes": [{ "type": "usage_anomaly" }],',
    '      "projectId": "projectId in (\'prj_123\')",',
    '      "autosubscribeOwnersInKnock": true',
    '    }',
    '',
    '  Built-in 4xx error anomaly rule:',
    '',
    '    {',
    '      "name": "Production 4xx error anomalies",',
    '      "alertTypes": [',
    '        {',
    '          "type": "error_anomaly",',
    '          "filter": "statusGroup eq \'4xx\'"',
    '        }',
    '      ],',
    '      "projectId": "projectId in (\'prj_123\')"',
    '    }',
    '',
    '  Custom threshold rule:',
    '',
    '    {',
    '      "name": "Checkout error rate",',
    '      "alertTypes": [{ "type": "custom_alert" }],',
    '      "customAlert": {',
    '        "queryJsonString": "{\\"event\\":\\"incomingRequest\\",\\"rollups\\":{\\"errors\\":{\\"measure\\":\\"count\\",\\"aggregation\\":\\"sum\\",\\"filter\\":\\"httpStatus ge 500\\"},\\"requests\\":{\\"measure\\":\\"count\\",\\"aggregation\\":\\"sum\\"}},\\"granularity\\":{\\"hours\\":1}}",',
    '        "triggerType": "threshold",',
    '        "triggerOperator": "gt",',
    '        "triggerThreshold": 0.05,',
    '        "formula": { "operator": "divide", "left": "errors", "right": "requests" },',
    '        "minThreshold": 20',
    '      }',
    '    }',
    '',
    '  Custom anomaly rule:',
    '',
    '    {',
    '      "name": "Edge request volume anomaly",',
    '      "alertTypes": [{ "type": "custom_alert" }],',
    '      "customAlert": {',
    '        "queryJsonString": "{\\"event\\":\\"incomingRequest\\",\\"rollups\\":{\\"requests\\":{\\"measure\\":\\"count\\",\\"aggregation\\":\\"sum\\"}},\\"groupBy\\":[\\"route\\"],\\"granularity\\":{\\"minutes\\":5}}",',
    '        "triggerType": "anomaly",',
    '        "triggerOperator": "gt",',
    '        "triggerThreshold": 3',
    '      }',
    '    }',
    '',
    '  Save one body to a JSON file, replace placeholders, then run:',
    '',
    '    $ vercel alerts rules add --body ./rule.json',
    '',
    '  Custom alert project targeting defaults to --project or the linked project.',
    '',
  ].join('\n');
}
